### ISSUE TITLE
a very weird issue

### ISSUE THREAD

**Issue by Mr-Frimman** [corpnewt/CorpBot.py#111]
here is the whole output of the .bat 
Git is not found in your PATH var!
Updates will be disabled!
Starting up 4 shards...
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\CorpBot.py-rewrite\Main.py", line 395, in <module>
    bot.run(settings_dict.get("token",""))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\shard.py", line 445, in connect
    raise item.error
discord.errors.PrivilegedIntentsRequired: Shard ID 0 is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Return code:  1
Starting up 4 shards...

**Comment by Mr-Frimman** [comment]
and this repeats over and over

**Comment by Mr-Frimman** [comment]
so sorry found out how to fix it
