### ISSUE TITLE
TypeError: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by sasdallas** [corpnewt/CorpBot.py#142]
So, originally, the bot refused to load ANY cogs, with the message that something wasn't awaited and that cg_man was NoneType. I was able to await the function, but now I get an error on Loading CogManager....:

```
Traceback (most recent call last):
  File "C:\Users\Samuel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Samuel\Desktop\Froggy Bot\Main.py", line 106, in on_all_shards_ready
    await bot.load_extension("Cogs.CogManager")
TypeError: object NoneType can't be used in 'await' expression
```

I don't know why, can someone help?

**Comment by sasdallas** [comment]
Nevermind, fixed by downloading new build.
