### ISSUE TITLE
heeeeeelp

### ISSUE THREAD

**Issue by ixKrooZ** [corpnewt/CorpBot.py#43]
hi 
i tried to use it in cloud 9 but not work
then i dawnload it in my pc
but get some errors
`  ###                ###
 # CorpBot - CorpNewt #
##############################
#          UPDATING          #
##############################

Trying to update via git...

fatal: Not a git repository (or any of the parent directories): .git

Traceback (most recent call last):
  File "C:\Users\DESKTOP\Desktop\CorpBot.py-rewrite/Main.py", line 43, in <modul
e>
    with open('token.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'token.txt'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x034BCFB0>
Return code:  1
Traceback (most recent call last):
  File "C:\Users\DESKTOP\Desktop\CorpBot.py-rewrite/Main.py", line 43, in <modul
e>
    with open('token.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'token.txt'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x034791B0>
Return code:  1

**Comment by camielverdult** [comment]
...

**Comment by corpnewt** [comment]
Looks like you didn't clone the bot via git (which is how you avoid the `fatal: Not a git repository (or any of the parent directories): .git` error), and it also looks like you haven't generated a token and placed it (no quotes, spaces, enters, or anything else) in a `token.txt` file in the same folder as the start scripts.

**Comment by ixKrooZ** [comment]
where is tokem.txt file <_<
http://prntscr.com/iit31x

**Comment by bisquitue** [comment]
It's a file where you put the token generated from a registered application on http://discordapp.com/developers/

**Comment by ixKrooZ** [comment]
ik i have the token
but idk where put it

**Comment by camielverdult** [comment]
In a file called token.txt. You have to make it.

**Comment by corpnewt** [comment]
You have to make your own - the token is kinda like the bot's username and password, so it's unique to each account.  You create a token via the link @bisquitue mentioned, then you paste it into a text file called `token.txt` and place that text file in the main folder (where you see Install.bat, etc).

**Comment by ixKrooZ** [comment]
guys plz i need help tell me how to setup it
i dawnloaded i zip file
then what shoud i do

**Comment by ixKrooZ** [comment]
guys plz contact me @!                        ო...❥ցƈ#8222

**Comment by camielverdult** [comment]
We've told you several times by now. You make a .txt file called token.txt, then you open token.txt and put the token you got from the discord developer platform in there. Save the file and first up the bot.

**Comment by ixKrooZ** [comment]
same problem
nothing change

**Comment by ixKrooZ** [comment]
`  ###                ###
 # CorpBot - CorpNewt #
###                ###


##############################
#          UPDATING          #
##############################


Trying to update via git...

fatal: Not a git repository (or any of the parent directories): .git

Traceback (most recent call last):
  File "D:\golemcraft2\CorpBot.py-rewrite/Main.py", line 43, in <module>
    with open('token.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'token.txt'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0306BED0>
Return code:  1
`

**Comment by ixKrooZ** [comment]
same problem

**Comment by ixKrooZ** [comment]
http://prntscr.com/iitcxf
this is token.txt file
guyyyys
heeeeelp me plz

**Comment by ixKrooZ** [comment]
###                ###
 # CorpBot - CorpNewt #
###                ###


##############################
#          UPDATING          #
##############################


Trying to update via git...

fatal: Not a git repository (or any of the parent directories): .git

Logged in as:
TEST#5729 (ID: 347671071257919488)

Invite Link:
https://discordapp.com/oauth2/authorize?client_id=347671071257919488&scope=bot&p
ermissions=8

Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\golemcraft2\CorpBot.py-rewrite/Main.py", line 56, in on_ready
    bot.load_extension("Cogs.CogManager")
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "D:\golemcraft2\CorpBot.py-rewrite\Cogs\CogManager.py", line 19, in setup

    bot.add_cog(CogManager(bot, settings))
  File "D:\golemcraft2\CorpBot.py-rewrite\Cogs\CogManager.py", line 48, in __ini
t__
    discord.Color.blurple(),
AttributeError: type object 'Colour' has no attribute 'blurple'

**Comment by corpnewt** [comment]
Don't post your token in public - like I said, that's your bot's username and password.  You wouldn't just post your username and pass on a random forum, would you?

As for the error - where are you putting the token.txt?

**Comment by ixKrooZ** [comment]
lol i delete my token im dont crazy
this is the new error help me plz
`  ###                ###
 # CorpBot - CorpNewt #
###                ###


##############################
#          UPDATING          #
##############################


Trying to update via git...

fatal: Not a git repository (or any of the parent directories): .git

Logged in as:
TEST#5729 (ID: 347671071257919488)

Invite Link:
https://discordapp.com/oauth2/authorize?client_id=347671071257919488&scope=bot&p
ermissions=8

Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\golemcraft2\CorpBot.py-rewrite/Main.py", line 56, in on_ready
    bot.load_extension("Cogs.CogManager")
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "D:\golemcraft2\CorpBot.py-rewrite\Cogs\CogManager.py", line 19, in setup

    bot.add_cog(CogManager(bot, settings))
  File "D:\golemcraft2\CorpBot.py-rewrite\Cogs\CogManager.py", line 48, in __ini
t__
    discord.Color.blurple(),
AttributeError: type object 'Colour' has no attribute 'blurple'
`

**Comment by ixKrooZ** [comment]
`  ###                ###
 # CorpBot - CorpNewt #
###                ###


##############################
#          UPDATING          #
##############################


Trying to update via git...

fatal: Not a git repository (or any of the parent directories): .git

Logged in as:
****************

Invite Link:
****************

Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\golemcraft2\CorpBot.py-rewrite/Main.py", line 56, in on_ready
    bot.load_extension("Cogs.CogManager")
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "D:\golemcraft2\CorpBot.py-rewrite\Cogs\CogManager.py", line 19, in setup

    bot.add_cog(CogManager(bot, settings))
  File "D:\golemcraft2\CorpBot.py-rewrite\Cogs\CogManager.py", line 48, in __ini
t__
    discord.Color.blurple(),
AttributeError: type object 'Colour' has no attribute 'blurple'
`

**Comment by corpnewt** [comment]
Likely the wrong discord.py version - no need to spam.  Take time, read your errors, and do some research on how to solve them.

**Comment by ixKrooZ** [comment]
```
Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py/Main.py", line 56, in on_re
ady
    bot.load_extension("Cogs.CogManager")
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py\Cogs\CogManager.py", line 1
9, in setup
    bot.add_cog(CogManager(bot, settings))
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py\Cogs\CogManager.py", line 4
8, in __init__
    discord.Color.blurple(),
AttributeError: type object 'Colour' has no attribute 'blurple'
```
help me on this plzzzzz

**Comment by bisquitue** [comment]
You still have an incorrect version of `discord.py`, get the latest from the rewrite branch.

**Comment by ixKrooZ** [comment]
`
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-p
ages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py/Main.py", line 56, in on
ady
    bot.load_extension("Cogs.CogManager")
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-p
ages\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py\Cogs\CogManager.py", lin
9, in setup
    bot.add_cog(CogManager(bot, settings))
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py\Cogs\CogManager.py", lin
8, in __init__
    discord.Color.greyple(),
AttributeError: type object 'Colour' has no attribute 'greyple'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-p
ages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py/Main.py", line 231, in o
essage
    context = await bot.get_context(message)
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-p
ages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attrib
 'get_context'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-p
ages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py/Main.py", line 231, in o
essage
    context = await bot.get_context(message)
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-p
ages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attrib
 'get_context'`

**Comment by ixKrooZ** [comment]
bot online now 
but not respond for any command

**Comment by ixKrooZ** [comment]
@corpnewt
