### ISSUE TITLE
sorry help me again

### ISSUE THREAD

**Issue by ixKrooZ** [corpnewt/CorpBot.py#44]
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py/Main.py", line 56, in on_re
ady
    bot.load_extension("Cogs.CogManager")
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py\Cogs\CogManager.py", line 1
9, in setup
    bot.add_cog(CogManager(bot, settings))
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py\Cogs\CogManager.py", line 4
8, in __init__
    discord.Color.greyple(),
AttributeError: type object 'Colour' has no attribute 'greyple'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py/Main.py", line 231, in on_m
essage
    context = await bot.get_context(message)
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute
 'get_context'`

**Comment by ixKrooZ** [comment]
@corpnewt 
@Goldfish64 
@1byte2bytes 
@Mercurial

**Comment by camielverdult** [comment]
You are being extremely annoying, please use common sense and/or google.

**Comment by 1byte2bytes** [comment]
>ping spamming anyone who has contributed
>expecting help immediately
🤔

**Comment by ixKrooZ** [comment]
nothing in google
plz help me guys

**Comment by 1byte2bytes** [comment]
Okay, so this is actually two different exceptions you've reported.
```
Ignoring exception in on_ready
Traceback (most recent call last):
File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\client.py", line 307, in _run_event
yield from getattr(self, event)(*args, **kwargs)
File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py/Main.py", line 56, in on_re
ady
bot.load_extension("Cogs.CogManager")
File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\ext\commands\bot.py", line 738, in load_extension
lib.setup(self)
File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py\Cogs\CogManager.py", line 1
9, in setup
bot.add_cog(CogManager(bot, settings))
File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py\Cogs\CogManager.py", line 4
8, in init
discord.Color.greyple(),
AttributeError: type object 'Colour' has no attribute 'greyple'
```
```
AttributeError: type object 'Colour' has no attribute 'greyple'
Ignoring exception in on_message
Traceback (most recent call last):
File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\client.py", line 307, in _run_event
yield from getattr(self, event)(*args, **kwargs)
File "D:\golemcraft2\CorpBot.py-rewrite\CorpBot.py/Main.py", line 231, in on_m
essage
context = await bot.get_context(message)
File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\discord\client.py", line 296, in getattr
raise AttributeError(msg.format(self.class, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute
'get_context'`
```
Learning how to format your issues would help in the future.

Also, we're volunteers under no obligation to help you. This behavior is also pretty childish, you sure you're old enough to have a GitHub account?

**Comment by red-green** [comment]
Running the bot is generally intended for someone who understands programming, or who is at least remotely intelligent...
