### ISSUE TITLE
Music is not working

### ISSUE THREAD

**Issue by BaroDevelopment** [corpnewt/CorpBot.py#88]
When i use the play command i get this error
```css
Ignoring exception in command play:
Traceback (most recent call last):
  File "E:\Programme\Python\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "E:\Downloads\CorpBot.py-rewrite\Cogs\Music.py", line 350, in play
    await self.resolve_search(ctx, url)
  File "E:\Downloads\CorpBot.py-rewrite\Cogs\Music.py", line 83, in resolve_search
    data = await self.add_to_queue(ctx, url, shuffle)
  File "E:\Downloads\CorpBot.py-rewrite\Cogs\Music.py", line 115, in add_to_queue
    tracks = await self.bot.wavelink.get_tracks(url)
  File "E:\Programme\Python\lib\site-packages\wavelink\client.py", line 100, in get_tracks
    return await node.get_tracks(query)
AttributeError: 'NoneType' object has no attribute 'get_tracks'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Programme\Python\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "E:\Programme\Python\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "E:\Programme\Python\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'get_tracks'
```

**Comment by corpnewt** [comment]
I [recently migrated](https://github.com/corpnewt/CorpBot.py/commit/1eab7a8e07c75b3dc7fe83de153434acb7305fc7) the play function to use [Lavalink](https://github.com/Frederikam/Lavalink/releases) via the [wavelink](https://github.com/PythonistaGuild/Wavelink) wrapper.  It now expects a local Lavalink server setup to play music.

In the error you pasted, the `node` is `None` - which means that wavelink returned a `NoneType` [here](https://github.com/corpnewt/CorpBot.py/blob/rewrite/Cogs/Music.py#L37-L46).

Let me know if setting up a local Lavalink server fixed the issue.

-CorpNewt

**Comment by corpnewt** [comment]
I'm going to close the issue for the time being - if that doesn't solve it for you, feel free to respond and I'll reopen it.

-CorpNewt

**Comment by BaroDevelopment** [comment]
I have setup an lavalink server and still face the same issue
